# Generated by Django 4.0.1 on 2022-05-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('titleName', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('totalPage', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('publishedDate', models.CharField(max_length=100)),
            ],
        ),
    ]
