# Generated by Django 4.0.1 on 2022-05-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RLibrary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
