# Generated by Django 4.0.1 on 2022-05-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RLibrary', '0004_book_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('completed', 'Completed'), ('plan to read', 'Plan to Read'), ('reading', 'Reading')], default='reading', max_length=100),
        ),
    ]
