# Generated by Django 4.0.1 on 2022-05-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RLibrary', '0005_alter_book_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
