# Generated by Django 4.1 on 2022-08-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RLibrary', '0007_alter_book_authors_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pageRead',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('completed', 'Completed'), ('plan to read', 'Plan to Read'), ('reading', 'Reading')], default='plan to read', max_length=100),
        ),
    ]
